import React from 'react';
import { Styled } from './styled';

export const Body = () => {
    return (
        <Styled.Body>                        
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dignissim enim sit amet venenatis urna. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Viverra suspendisse potenti nullam ac. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Et netus et malesuada fames ac turpis. In aliquam sem fringilla ut. Mattis enim ut tellus elementum sagittis vitae et leo duis. Nisl vel pretium lectus quam id leo in vitae turpis. Integer feugiat scelerisque varius morbi enim nunc faucibus. Suspendisse potenti nullam ac tortor vitae. Risus feugiat in ante metus dictum at tempor commodo. Sagittis orci a scelerisque purus semper eget duis at. Maecenas pharetra convallis posuere morbi leo. Sagittis nisl rhoncus mattis rhoncus urna. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Dolor purus non enim praesent elementum facilisis leo. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo.

            Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Id porta nibh venenatis cras sed felis. Gravida cum sociis natoque penatibus et. Suscipit tellus mauris a diam maecenas. Donec massa sapien faucibus et molestie ac feugiat sed. Suspendisse potenti nullam ac tortor vitae purus. Neque gravida in fermentum et sollicitudin. Rutrum quisque non tellus orci ac auctor augue. Vitae suscipit tellus mauris a diam maecenas sed enim. Ultricies mi quis hendrerit dolor magna eget est lorem. Ac tincidunt vitae semper quis lectus. At in tellus integer feugiat scelerisque varius morbi enim. Dapibus ultrices in iaculis nunc sed augue lacus viverra. Feugiat nisl pretium fusce id. Integer feugiat scelerisque varius morbi enim nunc. Leo in vitae turpis massa sed elementum tempus egestas sed.

            Elit duis tristique sollicitudin nibh sit amet commodo nulla. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. Lacinia quis vel eros donec. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Eleifend donec pretium vulputate sapien. Sagittis id consectetur purus ut. Elementum nisi quis eleifend quam adipiscing vitae proin. Faucibus a pellentesque sit amet porttitor eget dolor. Non sodales neque sodales ut etiam. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Ut consequat semper viverra nam libero justo laoreet sit amet. In fermentum et sollicitudin ac orci phasellus egestas tellus. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Placerat duis ultricies lacus sed turpis tincidunt id. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Leo integer malesuada nunc vel risus commodo. Amet volutpat consequat mauris nunc.

            Interdum posuere lorem ipsum dolor sit. Ut porttitor leo a diam sollicitudin. Neque laoreet suspendisse interdum consectetur. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Aliquam vestibulum morbi blandit cursus risus at ultrices mi tempus. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Neque egestas congue quisque egestas diam in arcu cursus. A lacus vestibulum sed arcu non odio euismod lacinia. Vel facilisis volutpat est velit egestas dui id ornare.

            Purus semper eget duis at tellus at. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Est placerat in egestas erat imperdiet sed. Enim sed faucibus turpis in eu mi bibendum neque. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Purus faucibus ornare suspendisse sed nisi lacus. Tortor at auctor urna nunc id cursus metus aliquam. Volutpat lacus laoreet non curabitur. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Porta nibh venenatis cras sed felis eget velit. Volutpat blandit aliquam etiam erat velit scelerisque in. Mauris augue neque gravida in fermentum.                             
        </Styled.Body>
    );
}